### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by roughpandaz** [xeewi/firebase-scrypt#5]
I'm getting the following error.

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at _promise2.default (/node_modules/firebase-scrypt/dist/firebaseScrypt.js:58:72)
    at new Promise (<anonymous>)
    at new F (/node_modules/core-js/library/modules/_export.js:36:28)
    at FirebaseScrypt.hash (/node_modules/firebase-scrypt/dist/firebaseScrypt.js:57:12)
    at FirebaseScrypt.verify (/node_modules/firebase-scrypt/dist/firebaseScrypt.js:88:17)
    at Object.<anonymous> (/testscrypt.js:15:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

This is my code. I'd love to get your input

```js
const firebaseScrypt = require("firebase-scrypt");

const input = {
  algorithm: "SCRYPT",
  base64_signer_key:
    "................",
  base64_salt_separator: "Bw==",
  rounds: 8,
  mem_cost: 14
};

const scrypt = new firebaseScrypt.FirebaseScrypt(input);

scrypt
  .verify(
    "123qwe123",
    "+0uSox1M774pFA==",
    "i8SlSWodxxMxqyo5hJu0pBcTWr7juYkngbmuE43g8yixC8XorL5mV8IqLzEPVIg3297pu+LzYA4mEwvy8q/G1Q=="
  )
  .then(isValid =>
    isValid ? console.log("Valid !") : console.log("Not valid !")
  )
  .catch(err => {
    console.log(err);
  });

```

**Comment by roughpandaz** [comment]
nvm. It was the object key's naming :)

For blind people like me.
It would be nice to be able to still accept snakecase variable names as that exported by firebase.

**Comment by xeewi** [comment]
Hello !

The main difference is that our repo is a tool for javascript already
implemented with 2 main function : hash and verify.

The repo from firebase is the C implementation :)

Hope it's help !

Le jeu. 5 nov. 2020 à 20:26, Rongxin Zhang <notifications@github.com> a
écrit :

**Comment by roughpandaz** [comment]
Merci!
